### ISSUE TITLE
Tri Freq count in Exon level

### ISSUE THREAD

**Issue by fitbio** [nriddiford/mutationProfiles#3]
Hello I have seen an option to calculate Trifreq count in an genome level. Is it possible to calculate the triFreq count to the exon level?

**Comment by nriddiford** [comment]
I've added new function [getTriFromFasta](https://github.com/nriddiford/mutationProfiles/blob/master/R/triCount.R) that should uses the [trinucleotideFrequency](http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/Biostrings/html/nucleotideFrequency.html) function from BioStrings to calculate the Tri freq from a supplied fasta file (genome, exome). This should (although I haven't tested this extensively) give the same results as my `triFreq` function.

You should be able to use the returned `df` as a `tri.counts.method` in [whichSignatures](https://github.com/raerose01/deconstructSigs/blob/master/R/whichSignatures.R)

**Comment by fitbio** [comment]
Thank you very much for your reply. Yes I have used which signatures function from deconstructSigs.
Right now, I actually calculated the trinucleotide freuquency manually for only exonic sequences using my exon bed file with chromosomes 1-22,X and Y.
Here are my steps
#########################
v20130108.exome.targets<-`20130108.exome.targets`
exons_Granges<-GRanges(seqnames = v20130108.exome.targets$V1,IRanges(start = v20130108.exome.targets$V2,end=v20130108.exome.targets$V3))

exonic_sequences<-getSeq(BSgenome.Hsapiens.UCSC.hg19,exons_Granges)

trifreq_exons<-trinucleotideFrequency(exonic_sequences)

colSums(trifreq_exons)

#################################################################################

But when I compare my trifreq counts with tri.counts.exome from deconstructSigs the values in my data seems to be pretty high. Is it possible  if you can suggest me If I am wrong with any of my steps?

**Comment by nriddiford** [comment]
I think it's because you want a scaling factor (1/tricount) - see https://github.com/raerose01/deconstructSigs/issues/20

I have no involvement with deconstructSigs though so you're better off asking [here](https://github.com/raerose01/deconstructSigs/issues)

**Comment by fitbio** [comment]
Thank you very much for your reply. :)
